# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: ebc9050d3d3434417feff68e3d847ad4123f5ba8
    hooks:
    -   id: fmt
    -   id: cargo-check

-   repo: local
    hooks:
    -  id: nixpkgs-fmt
       name: nixpkgs-fmt
       description: Format nix code with nixpkgs-fmt.
       entry: cargo run --
       language: rust
       files: \.nix$
       always_run: true
       minimum_pre_commit_version: 1.14.2
       exclude: >
           (?x)^(
               nix/sources.nix|
               test_data/.*
           )$
