language: nix

script: |
  export TMPDIR=$HOME/tmpdir
  mkdir -p "$TMPDIR"
  ./ci.sh

branches:
  only:
    - staging
    - master
    - trying

deploy:
  skip_cleanup: true
  provider: script
  script: TMPDIR=$HOME/tmpdir ./deploy.sh
  on:
    branch: master
