[package]
name = "nixpkgs-fmt"
version = "0.3.1"
authors = [
  "Aleksey Kladov <aleksey.kladov@gmail.com>",
  "zimbatm <zimbatm@zimbatm.com>"
]
edition = "2018"
license = "Apache-2.0"
description = "Nix code formatter for nixpkgs"
repository = "https://github.com/nix-community/nixpkgs-fmt"

[workspace]
members = [ "./wasm" ]

[dependencies]
clap = "2.33.0"
rnix = { git = "https://github.com/nix-community/rnix-parser.git" }

[dev-dependencies]
unindent = "0.1.3"
