name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@v3
      with:
        name: nixpkgs-fmt
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        skipNixBuild: true
    - run: ./ci.sh
    - uses: actions/upload-artifact@v1
      with:
        name: wasm
        path: wasm
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v1
      with:
        name: wasm
    - run: ./deploy.sh
      env:
        DEPLOY_SSH_KEY: '${{ secrets.DEPLOY_SSH_KEY }}'
